[package]
name = "ioc"
version = "0.1.0"
authors = ["Igor Bykov <con29rus@live.ru>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
resolve_macro = { path="./resolve_macro" }
